#
# ██████╗██    ██╗  ███═╗ ██████╗ ██████╗ █████╗  █████╗ ██████╗  ██████╗
#██╔════╝███╔═███║ ██ ██╚╗██╔══██╗  ██╔═╝██╔══██╗██╔══██╗██╔══██╗██╔════╝
#╚█████╗ ██╔██╗██║██╔══██║██████╔╝  ██║  ██║  ██║██║  ██║██████╔╝╚█████╗
# ╚═══██╗██║  ║██║███████║██╔══██╗  ██║  ██║  ██║██║  ██║██╔═══╝  ╚═══██╗
#██████╔╝██║  ║██║██╔══██║██║  ██║  ██║  ╚█████╔╝╚█████╔╝██║     ██████╔╝
#╚═════╝ ╚═╝  ╚══╝╚═╝  ╚═╝╚═╝  ╚═╝  ╚═╝   ╚════╝  ╚════╝ ╚═╝     ╚═════╝
#
#Plugin development by SmartOops | VK: vk.com/smartoops | Thanks for download!
#Commands: В данном плагине отсутствуют команды
#Permissions: Указанны в самом низу данного файла

Settings:
  noDamage: true #Запретить урон
  noHunger: true #Запретить голод
  noBreak: true #Запретить ломать блоки
  noPlace: true #Запретить ставить блоки
  noFire: true #Запретить распространение огня и поджогов
  noExplosions: true #Запретить взрывы
  noMessage: true #Отключить сообщения при входе/выходе/кике/смерти и т.д
  noChat: true #Отключить чат
  noCommands: true #Отключить использование команд
  GameMode: ADVENTURE #Какой режим будет на сервере у игроков

allowed_commands: #Работает только если - noCommands: true
  - menu #Здесь нужно указать команды, которые будут активны, даже при - noCommands: true
  - donate

Effects:
  Invisibility: true #Перевод игроков в режим невидимости
  Speed: true #Будет-ли эффект скорости у игроков на сервере
  BlindNess: true #Будет-ли эффект слепоты у игроков на сервере

LvlonJoin:
  enabled: true # Включить выдачу опыта при заходе
  amount: 777 # Кол-во опыта, которое будет отображаться на EXP-баре

Time:
  fixed: true # Зафиксировать время в мире
  meaning: 15000 # Значение на котором зафиксировать
  #Значение - meaning: 0 - День
  #Значение - meaning: 15000 - Ночь

Permissions:
  bypassChat: "bypassChat" # Право писать в чат, если он отключён
  bypassCommands: "bypassCommands" # Право писать команды в чат
  bypassBreak: "bypassBreak" # Право ломать блоки, если это запрещено
  bypassPlace: "bypassPlace" # Право ставить блоки, если это запрещено